name: Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    if: |
      contains(github.event.head_commit.message , 'docs:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '23.6'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec nx build docs
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/docs/.vitepress/dist --project-name=anki-eco
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy redirect
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/docs/legacy --project-name=ikkz-template
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
