name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry: ['mcq', 'tf', 'basic', 'mcq_10', 'match', 'cloze']
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.6'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build --e2e --entry=${{matrix.entry}}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm e2e-test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{matrix.entry}}
          path: playwright-report/
          retention-days: 30
