name: Release

on:
  push:
    branches:
      - legacy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.6'
          cache: 'pnpm'
      - run: pnpm install
      - name: Build templates
        run: pnpm run build

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'
      - name: Gen APKG
        run: pnpm run package
      - name: Build playground
        run: pnpm run pg-build

      - name: Publish playground
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ikkz-template'
          directory: 'playground/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
